[project]
site_name = "Homelab Docs"
site_description = "Documentation for my homelab setup"
site_author = "James Young"
docs_dir = "docs"

[project.theme]
variant = "modern"

# dark mode settings
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]] 
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
