on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/cloudflare-pages-deployment.yml
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/cloudflare-pages-deployment.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Zensical Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: zensical build --clean
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name=jyyhomelab-landingpage --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
